### ISSUE TITLE
berryboot images

### ISSUE THREAD

**Issue by tristan-k** [SupervisedThinking/LibreELEC-RR#2]
I tried to convert the rpi4 image to a berryboot compatible squashfs image but I failed. There is berryboot image [available](https://sourceforge.net/projects/berryboot-updated-images/files/Raspberry-Pi/libreelec_rr_builds_kodi_18_leia_rpi2_rpi3_2019.04.04_berryboot.img.gz/download) for the old version for rpi2/3 but not for your updated version. Can you provide instructions on how to convert the image or host a berryboot image for your version?

**Comment by SupervisedThinking** [comment]
Did you follow these steps? https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions I've never created a beeryboot image & have to RPi4 to test.

**Comment by tristan-k** [comment]
I did but the tutorial is only applicable for images with a specific partition layout. The LibreElec image itself provides a SquashFS image which has to be modified. There is also [this github repo](https://github.com/macmpi/berryboot-scripts) which tries to [patch](https://github.com/macmpi/berryboot-scripts/blob/master/LibreELEC/berryboot-init) the `SYSTEM` SquashFS image but sadly it's broken and written for vanilla LibreElec. I can test the image for you if you decide to support berryboot.

**Comment by SupervisedThinking** [comment]
A LibreELEC-RR image uses the same SquashFS and the same partition layout as vanilla LE there is literally zero difference. So if it's working with vanilla LE it's working with mine too since I just add packages & adjust scripts to run them.

**Comment by tristan-k** [comment]
No, it's not working with vanilla LE. I said that the berryboot documentation was written for images in mind **which do not in itself** provide a SquashFS image. Furthermore there is another [script](https://github.com/macmpi/berryboot-scripts/blob/master/LibreELEC/berryboot-init) which tries to circumvent this issue but which is [broken](https://github.com/macmpi/berryboot-scripts/issues/14) with rpi4 and recent LE versions. We need someone who knows how to modify the LibreELEC-RR image or for that matter the vanilla LibreELEC image in order to boot with berryboot. It has [been done](https://sourceforge.net/projects/berryboot-updated-images/files/Raspberry-Pi/libreelec_rr_builds_kodi_18_leia_rpi2_rpi3_2019.04.04_berryboot.img.gz/download) in the past.
