### ISSUE TITLE
[BUG] Default audio options give no output on RPI4

### ISSUE THREAD

**Issue by domb84** [SupervisedThinking/LibreELEC-RR#3]
### Describe the bug
The options in the RR Configuration tool cannot be configured in such a way to allow RetroArch to output audio. The RR Configuration tool is also disabled by default.

### To Reproduce
Steps to reproduce the behaviour:
1. Open the RR Configuration tool
2. Choose any audio backend or output device
3. Audio driver fails to load in RetroArch

### Information
 - LE Version: 10.0.0
 - Hardware Platform: RPi4

### Log file
```[INFO] [KMS]: New FB: 4096x2160 (stride: 16384).
[INFO] [KMS]: New FB: 4096x2160 (stride: 16384).
[INFO] [Config]: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
[INFO] FRONTEND_FORK_RESTART
[ERROR] failed_to_start_audio_driver
[ERROR] failed_to_start_audio_driver
[ERROR] failed_to_start_audio_driver
[INFO] [Config]: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
```

### Additional context
To get working audio on the RPi4 i performed the following:

1. Disable RR Configuration tool
2. Blacklist snd_soc_skl (unsure if this is necessary)
3. Check retroarch --features
```
CoreAudio:
                Audio driver: no
  CoreAudioV3:
                Audio driver: no
  ALSA:
                Audio driver: yes
  OSS:
                Audio driver: no
  Jack:
                Audio driver: no
  RSound:
                Audio driver: no
  RoarAudio:
                Audio driver: no
  PulseAudio:
                Audio driver: yes
  DirectSound:
                Audio driver: no
  WASAPI:
                Audio driver: no
  XAudio2:
                Audio driver: no
  OpenAL:
                Audio driver: no
  OpenSL:
                Audio driver: no
```
4. Select SDL2 as output device
5. Audio now works
6. No combination of ALSA or PulseAudio gives audio output. Perhaps an SDL2 option can be added to RR Configuration

**Comment by josemata00** [comment]
> ### Describe the bug
> The options in the RR Configuration tool cannot be configured in such a way to allow RetroArch to output audio. The RR Configuration tool is also disabled by default.
> 
> ### To Reproduce
> Steps to reproduce the behaviour:
> 
> 1. Open the RR Configuration tool
> 2. Choose any audio backend or output device
> 3. Audio driver fails to load in RetroArch
> 
> ### Information
> * LE Version: 10.0.0
> * Hardware Platform: RPi4
> 
> ### Log file
> ```
> [INFO] [KMS]: New FB: 4096x2160 (stride: 16384).
> [INFO] [Config]: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
> [INFO] FRONTEND_FORK_RESTART
> [ERROR] failed_to_start_audio_driver
> [ERROR] failed_to_start_audio_driver
> [ERROR] failed_to_start_audio_driver
> [INFO] [Config]: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
> [INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
> [INFO] [Core]: Unloading core..
> [INFO] [Core]: Unloading core symbols..
> [INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
> ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> ALSA lib /build/LibreELEC-RR/build.LibreELEC-RPi4.arm-10.0-devel/build/alsa-lib-1.2.4/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
> ```
> 
> ### Additional context
> To get working audio on the RPi4 i performed the following:
> 
> 1. Disable RR Configuration tool
> 2. Blacklist snd_soc_skl (unsure if this is necessary)
> 3. Check retroarch --features
> 
> ```
> CoreAudio:
>                 Audio driver: no
>   CoreAudioV3:
>                 Audio driver: no
>   ALSA:
>                 Audio driver: yes
>   OSS:
>                 Audio driver: no
>   Jack:
>                 Audio driver: no
>   RSound:
>                 Audio driver: no
>   RoarAudio:
>                 Audio driver: no
>   PulseAudio:
>                 Audio driver: yes
>   DirectSound:
>                 Audio driver: no
>   WASAPI:
>                 Audio driver: no
>   XAudio2:
>                 Audio driver: no
>   OpenAL:
>                 Audio driver: no
>   OpenSL:
>                 Audio driver: no
> ```
> 
> 1. Select SDL2 as output device
> 2. Audio now works
> 3. No combination of ALSA or PulseAudio gives audio output. Perhaps an SDL2 option can be added to RR Configuration

On RPi4, connected HDMI0, uses RR Tool (Default option with HDMI0), and on Retroarch Sound Config, use hdmi:CARD=vc4hdmi0,DEV=0 what audio device. If you use HDMI1, then change hdmi0 with hdmi1. Restart and working audio.

NOTE: Use ALSA in both configs.

**Comment by domb84** [comment]
I find this only works if the following is true. My TV is connected to HDMI 0.

RR-Config tool, set to:

hdmi:CARD=vc4hdmi0,DEV=1

Retroarch set to:

hdmi:CARD=vc4hdmi0,DEV=0

I have to manually set the config in retroarch, else no audio works.

Set both to ALSA.

I don't know why the above config works as it's incorrect, but it's as though the devices are reversed in rr-config tool.

**Comment by domb84** [comment]
Appears resolved in latest release.
