### ISSUE TITLE
[BUG] mupen64plus_next on rpi4 crashes with segfault

### ISSUE THREAD

**Issue by domb84** [SupervisedThinking/LibreELEC-RR#4]
### Describe the bug
Current release for rpi4 includes mupen64plus which crashes with a seg fault

### To Reproduce
1. Launch an n64 game using mupen64_next on rpi4
2. Segmentation fault
3. 
### Informations
 - LE Version: [e.g. 10.0]
 - Hardware Platform: [e.g. RPi4]

### Additional context
Replaced with mupen64plus_next_libretro.so from latest rpi4 lakka nightly and the issue is resolved.

https://nightly.builds.lakka.tv/latest/RPi4.arm/Lakka-RPi4.arm-nightly-20210828-497be54.tar

**Comment by josemata00** [comment]
> ### Describe the bug
> Current release for rpi4 includes mupen64plus which crashes with a seg fault
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Launch an n64 game using mupen64_next on rpi4
> 2. Segmentation fault
> 
> ### Informations
> * LE Version: [e.g. 10.0]
> * Hardware Platform: [e.g. RPi4]
> 
> ### Log file
> ### Additional context
> Replaced with mupen64plus_next_libretro.so from latest rpi4 lakka nightly and the issue is resolved.
> 
> https://nightly.builds.lakka.tv/latest/RPi4.arm/Lakka-RPi4.arm-nightly-20210828-497be54.tar

Hello. You can share this .so file? I have same problem with LibreElec RR..

**Comment by domb84** [comment]
This is the version I'm using, but i just extarcted it from lakka, so I'm sure you can do the same with the latest image.

https://mega.nz/file/5D4HwSya#NgNiZ0ke40dueeHEU_7OH--39cqQpifqEg-YbXsyqYU

**Comment by josemata00** [comment]
R  This is the version I'm using, but i just extarcted it from lakka, so I'm sure you can do the same with the latest image.
> 
> https://mega.nz/file/5D4HwSya#NgNiZ0ke40dueeHEU_7OH--39cqQpifqEg-YbXsyqYU
Where should that file be copied? In which folder exactly? Thanks for your help.
