### ISSUE TITLE
[BUG][RPi4] Build failure caused by freeimage cross-compile error on Ubuntu 20.04 ARM

### ISSUE THREAD

**Issue by pretoriano80** [SupervisedThinking/LibreELEC-RR#8]
### Describe the bug
Building is failing due to an error caused by freeimage cross-compiling error

### To Reproduce
1. Start building for RPi4 on Ubuntu 20.04 Arm (aarch64)

### Informations
 - LE Version: LibreELEC-RR master (rev. 08d3bca )
 - Hardware Platform: RPi4 8GB
 - Build System: Ubuntu 20.04 ARM64 (aarch64)

### Log file
[309.log](https://github.com/SupervisedThinking/LibreELEC-RR/files/8311628/309.log)

**Comment by SchwingMC** [comment]
Have you tried to build with Linux Mint? I build libreelec-10-rr a few days ago and it worked well. I'm Cillit from the libreelec forums, who reported building problems. This was solved by switching to Linux Mint. Also see my comments on the current master builds in the libreelec forums, they might not work as intended.

**Comment by pretoriano80** [comment]
@SchwingMC no i didn't tried on Linux Mint, but in my case is probably an architecture issue cause i'm using the ARM version of Ubuntu 20.04.
It's an Oracle Always Free VM instance which i'm using as main dev environment.

I know there are some issues after the python bump, but i'm trying to build LibreELEC-RR also for finding issues with the build env (like this one) and testing other things on my RPi4.
I'm sure these python issues will be fixed at some point, but i'm not holding my breath because of it either.

**Comment by SupervisedThinking** [comment]
@pretoriano80 could you test if https://github.com/SupervisedThinking/LibreELEC-RR/commit/9fba90a22d6e06d95db8e309fb76d31a29e3933b fixes your build failure? I guess `+pic` should fix it

**Comment by pretoriano80** [comment]
Yes , https://github.com/SupervisedThinking/LibreELEC-RR/commit/9fba90a22d6e06d95db8e309fb76d31a29e3933b fixed it,thank you.
